### ISSUE TITLE
Review Database Schema

### ISSUE THREAD

**Issue by Scholars-Mate** [Scholars-Mate/Flask-Cards#8]
I changed the schema a little bit, and was wanting you guys to look over it. As far as I can tell, it does everything we need it to, and is at least third normal form.

[New schema](/Scholars-Mate/Flask-Cards/blob/docs/schema/docs/Schema.md)

**Comment by kawaiiastronaut** [comment]
The Set<->Card relationship is intended to be many to many. Does this current schema allow this? Each card contains a setId, since that is the case wouldn't it limit the amount of sets the card is in to one? Otherwise assigning a card to a different set would mean changing the internal setId of the card, right?

**Comment by Scholars-Mate** [comment]
It's easier to make the Set<->Card relationship one to many. I can't imagine it would be a common use case to have a card belong to several sets.

**Comment by kawaiiastronaut** [comment]
That makes sense. It would be too much work for such a short time span, I just thought that was the original intent. That would be something to consider if this were an actual permanent website rather than a school project, I suppose.

Other than that, the schema doesn't have any gaping holes in it, none that would be obvious to me until something stopped working, at least.

**Comment by yuichiu416** [comment]
In my original idea, I think different card sets can be:
set1: classnote
set2: English vocabulary
set3: shopping list

In this case, they're just one to many?
What will it look like if it's many to many?

**Comment by Scholars-Mate** [comment]
Those are one to many.
Many to many would mean that each set would consist of many cards, and each card could belong to many sets.

**Comment by Scholars-Mate** [comment]
I'll be closing this issue in a few hours if no one has any other comments so Roger and I can get to work with the database.
